export const Users = [
  {
    Profile: "/images/user8/profile.jpg",
    IsVideo: true,
    ImgNum: 1,
    img1: "/images/user8/1.mp4",
    Username: "@Kapwa",
    Caption: "Replying to @ikemalupit",
    Likes: "57.7k",
    Dislikes: "437",
    Comments: "5602",
  },
  {
    Profile: "/images/user9/profile.jpg",
    IsVideo: true,
    ImgNum: 1,
    img1: "/images/user9/1.mp4",
    Username: "@Motokalbo",
    Caption: "Solid pag naka full #jvt",
    Likes: "2,116",
    Dislikes: "199",
    Comments: "15",
  },
  {
    Profile: "/images/user7/profile.jpeg",
    IsVideo: true,
    ImgNum: 1,
    img1: "/images/user7/1.mp4",
    Username: "@modchieworks",
    Caption: "mio 232 4v LC,AC,OC",
    Likes: "1,112",
    Dislikes: "62",
    Comments: "136",
  },
  {
    Profile: "/images/user1/profile.jpg",
    IsVideo: false,
    ImgNum: 4,
    img1: "/images/user1/1.jpg",
    img2: "/images/user1/2.jpg",
    img3: "/images/user1/3.jpg",
    img4: "/images/user1/4.jpg",
    Username: "@andreike09",
    Caption:
      "My buddies and I hit the road for an epic adventure to Baguio City, where we laughed, bonded, and took in the stunning sights along the way, making memories that'll last a lifetime.",
    Likes: "40k",
    Dislikes: "3.3k",
    Comments: "2.2k",
  },
  {
    Profile: "/images/user2/profile.jpg",
    IsVideo: false,
    ImgNum: 2,
    img1: "/images/user2/1.jpg",
    img2: "/images/user2/2.jpg",
    Username: "@skibidikwak2x",
    Caption:
      "quickie karga session on my motorcyle. Looks squiky clean... #quicky #malambing",
    Likes: "3",
    Dislikes: "0",
    Comments: "27",
  },
  {
    Profile: "/images/user3/profile.jpg",
    IsVideo: false,
    ImgNum: 3,
    img1: "/images/user3/1.jpg",
    img2: "/images/user3/2.jpg",
    img3: "/images/user3/3.jpg",
    img4: "/images/user3/4.jpg",
    Username: "@Aeaeron",
    Caption:
      "Help pls! my motorcyle became slow when i stumble upon some Potholes what shold I do",
    Likes: "20m",
    Dislikes: "1k",
    Comments: "3k",
  },
  {
    Profile: "/images/user4/profile.jpg",
    IsVideo: false,
    ImgNum: 0,
    Username: "@Copeland. kenneth",
    Caption:
      "Planning to buy a new motorcyle for fun. Do you guys have a Suggestion on  what should a beginner to ride?",
    Likes: "4k",
    Dislikes: "20k",
    Comments: "6.9k",
  },
  {
    Profile: "/images/user5/profile.jpg",
    IsVideo: false,
    ImgNum: 1,
    img1: "/images/user5/1.jpg",
    Username: "@mynameisnotjeff",
    Caption: "Some where in the sea",
    Likes: "34k",
    Dislikes: "1k",
    Comments: "10k",
  },
  {
    Profile: "/images/user6/profile.jpg",
    IsVideo: true,
    ImgNum: 1,
    img1: "/images/user6/1.mp4",
    Username: "@donut ace",
    Caption: "Close one!",
    Likes: "3.5k",
    Dislikes: "100",
    Comments: "2.2k",
  },
];
